allowBuilds:
  '@cloudflare/workerd-darwin-arm64': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - workerd
