export const cciCopy = {
  en: {
    meta: {
      title: "Century City Index — Morris Liu",
      description:
        "A transparent scenario index for comparing the long-horizon resilience and opportunity of functional urban areas.",
    },
    nav: { index: "Index", method: "Method", releases: "Releases", language: "中文" },
    runtime: {
      loading: "Loading the immutable release data.",
      ready: "Release data loaded.",
      loadError:
        "Interactive controls are unavailable because the release data could not be loaded.",
      metric: "Metric",
      officialResult: "Official result",
      range: "Robust–Upside range",
      confidence: "Confidence",
      tail: "Tail status",
    },
    hero: {
      title: "Century City Index",
      intro:
        "A scenario index for asking which urban systems may remain viable, capable, and connected across a changing century.",
      caveat: "Conditional scenarios, not a forecast or recommendation.",
      chartTitle: "One city, many futures",
      chartNote: "Structure only — not a city result",
      robust: "Robust",
      median: "Median",
      upside: "Upside",
    },
    release: {
      release: "Release",
      asOf: "As of",
      model: "Model",
      data: "Data",
      boundary: "Boundary",
      sourceManifest: "Source manifest",
      researchPreview: "Research preview",
      research_preview: "Research preview",
      candidate: "Candidate",
      published: "Published",
      immutable: "Immutable release",
      checksums: "Source and output checksums",
      reviewed: "Versioned evidence reviews",
      download: "Open release JSON",
    },
    controls: {
      targetYear: "Target year",
      resultMode: "Result mode",
      robust: "Robust",
      median: "Median",
      upside: "Upside",
      lifetime: "Lifetime",
    },
    compare: {
      title: "Compare the pilot cities",
      intro:
        "A deliberately diverse validation panel, bound to one globally consistent functional urban area product.",
      notice: "No city clears v1 ranking eligibility yet. Missing evidence remains missing.",
      compare: "Compare",
      clear: "Clear comparison",
      selected: "Selected cities",
      empty: "Select up to three cities from the table.",
      why: "Why no ranks?",
      columns: {
        city: "City / FUA",
        result: "Result",
        range: "Range",
        confidence: "Confidence",
        tail: "Tail",
        evidence: "Evidence",
      },
      inAudit: "In audit",
      reviewed: "Reviewed · see evidence",
      notRanked: "Not Ranked",
      notRankedDefinition: "eligibility gate not met",
      confidenceDefinition: "one or more confidence dimensions are unsupported",
      noClaimDefinition: "no claim is made",
      selectCity: "Select city for comparison",
      openCity: "Open city evidence",
    },
    city: {
      boundaryPending: "Boundary scope not verified",
      boundaryVerified: "Boundary mapping verified",
      notRanked: "Not Ranked",
      overview: "Overview",
      evidence: "Evidence",
      sources: "Sources",
      eightDimensions: "Eight dimensions",
      result: "Result",
      confidence: "Confidence",
      evidenceStatus: "Evidence",
      inAudit: "In audit",
      subpillars: "Subpillars",
      noEvidence: "No scored evidence has passed the release gate.",
      eligibilityReasons: "Open eligibility blockers",
      boundaryRecord: "Boundary record",
      eFuaIds: "eFUA IDs",
      urbanCentreIds: "Urban-centre IDs",
      sourceNames: "Source names",
      localLanguages: "Required local evidence languages",
      audit: "Evidence review",
      usable_observation: "Local observation found; scoring fit not established",
      context_only: "Context only; excluded from city scoring",
      insufficient_evidence: "Insufficient evidence for this dimension",
      observationBoundary: "Observation geography review",
    },
    dimensions: {
      PCS: { name: "Physical & climate safety", weight: 15 },
      GSS: { name: "Geopolitical safety", weight: 15 },
      ISR: { name: "Institutional & social resilience", weight: 15 },
      RES: { name: "Essential resources", weight: 10 },
      MED: { name: "Medical capability", weight: 15 },
      LON: { name: "Longevity translation", weight: 10 },
      TEC: { name: "Technological capacity", weight: 10 },
      OPT: { name: "Optionality & exit", weight: 10 },
    },
    subpillars: {
      heat_humidity: "Heat & humidity",
      flood_sea_level: "Flood & sea level",
      geophysical: "Geophysical hazard",
      severe_weather_wildfire: "Severe weather & wildfire",
      organized_violence: "Local organized violence",
      regional_conflict: "Regional & interstate conflict",
      strategic_exposure: "Strategic target & coercion exposure",
      governance: "Governance & rule implementation",
      adaptive_capacity: "Fiscal & adaptive capacity",
      social_cohesion: "Social cohesion",
      emergency_recovery: "Emergency recovery",
      water: "Water",
      food: "Food",
      energy: "Energy",
      supply_chain: "Supply-chain redundancy",
      access: "Access & financial protection",
      routine_quality: "Routine & acute quality",
      specialist_capacity: "Complex specialist capacity",
      system_continuity: "System continuity",
      translation: "Longevity-specific translation",
      trial_maturity: "Clinical-trial maturity",
      regulatory_adoption: "Regulatory adoption",
      resident_access: "Resident access",
      knowledge_output: "Frontier knowledge output",
      industry_density: "Company & industry density",
      digital_infrastructure: "Compute & digital infrastructure",
      diffusion: "Technology diffusion",
      transport_redundancy: "International transport redundancy",
      legal_mobility: "Legal mobility & exit",
      asset_portability: "Asset portability",
      network_continuity: "External network continuity",
    },
    myCci: {
      title: "My CCI",
      intro:
        "Adjust only the eight dimension weights. The official release, confidence, sources, and tail status never change.",
      total: "Total",
      reset: "Reset to official",
      personalResult: "Personal result",
      unavailable: "Unavailable while ranking eligibility is not met.",
      weightLabel: "weight",
    },
    tail: {
      title: "Tail tests",
      status: "Status",
      note: "Note",
      unassessed: "Unassessed",
      insufficient: "Reviewed evidence does not establish a 2125 outcome",
      pass: "Pass",
      watch: "Watch",
      fail: "Fail",
      fatal_heat_humidity: "Fatal heat & humidity",
      permanent_inundation: "Permanent inundation",
      geophysical_catastrophe: "Geophysical catastrophe",
      conflict_strategic_exposure: "Conflict & strategic exposure",
      essential_system_interruption: "Essential-system interruption",
    },
    evidenceLevels: {
      city_observation: {
        title: "City observation",
        note: "Directly observed within the city or FUA.",
      },
      national_prior: {
        title: "National prior",
        note: "Inferred from country-level conditions.",
      },
      scenario_assumption: {
        title: "Scenario assumption",
        note: "Forward-looking or modelled scenario input.",
      },
      missing: "Missing evidence stays visible; no silent fill.",
    },
    method: {
      title: "How the index works",
      intro:
        "A visible chain from evidence to conditional outcomes. No language model assigns scores.",
      steps: [
        { number: "01", title: "Observe", note: "city observations and qualified priors" },
        { number: "02", title: "Normalize", note: "fixed bad / reference / good anchors" },
        {
          number: "03",
          title: "Project",
          note: "baseline + horizon × scenario delta × observed sensitivity",
        },
        { number: "04", title: "Summarize", note: "P20 Robust / P50 Median / P80 Upside" },
        { number: "05", title: "Gate", note: "confidence, sensitivity, eligibility, tail tests" },
      ],
      scenariosTitle: "Twenty-seven core scenarios",
      climate: "Climate",
      geopolitics: "Geopolitics",
      medicine: "Medicine",
      climateStates: ["Stabilization", "Middle", "High stress"],
      geopoliticsStates: ["Cooperation", "Fragmentation", "Escalation"],
      medicineStates: ["Incremental", "Geroscience breakthrough", "Regenerative platform"],
      unweighted: "The grid is unweighted. It does not pretend to know scenario probabilities.",
      confidenceTitle: "Confidence is not averaged",
      confidenceMeasures: [
        "Geographic fit",
        "Source independence",
        "Freshness",
        "Method & provenance",
        "Horizon support",
      ],
      weakest: "Overall confidence is the weakest grade.",
      lifetime:
        "Lifetime is the undiscounted, time-weighted mean of Point results from the release date through the target year, with linear interpolation between target years.",
    },
    governance: {
      title: "Data without a default authority",
      intro:
        "CCI does not presume that an international body, government, NGO, company, remote-sensing product, or English-language index is neutral.",
      principles: [
        "Classify how a number was produced separately from who published it.",
        "Keep upstream lineages so two brands using one dataset do not count as independent evidence.",
        "Require local-language evidence searches for all eight dimensions in every pilot city.",
        "Substitute and recompute contested inputs; never average ideological camps or add a correction coefficient.",
      ],
      manifest: "Source manifest",
      manifestSummary: "Open the catalogued source families and their known limits",
      source: "Source",
      role: "Release role",
      mechanism: "Production mechanism",
      limits: "Known coverage limits",
      applied: "Applied",
      catalogued: "Catalogued, not scored",
      context_only: "Context only",
      fullPolicy: "Read the full data and bias governance policy",
    },
    releases: {
      title: "Release history",
      release: "Release",
      asOf: "As of",
      model: "Model",
      data: "Data",
      boundary: "Boundary",
      status: "Status",
    },
    correction: {
      title: "Challenge the evidence",
      intro:
        "Found a stronger source or a broken transformation? Open a correction with the city, indicator, release, reason, and verifiable source.",
      link: "Open a correction on GitHub",
    },
    footer: {
      methodology: "Methodology",
      governance: "Data & bias governance",
      manifest: "Source manifest",
      back: "Back to Morris Liu",
    },
    reasons: {
      boundary_needs_review: "FUA scope is not verified",
      indicator_registry_incomplete: "indicator registry is not frozen",
      subpillar_evidence_incomplete: "one or more subpillars have no calculable evidence",
      indicator_provenance_incomplete: "one or more scored inputs lack complete provenance",
      observed_coverage_below_85: "observed coverage is below 85%",
      local_evidence_packs_incomplete: "local-language evidence packs are incomplete",
      alternative_source_checks_incomplete: "required alternative-source checks are incomplete",
      source_sensitivity_missing: "source-substitution sensitivity is not recorded",
      unresolved_source_conflict: "a source conflict can change eligibility",
      confidence_grade_d: "one or more confidence measures are grade D",
      future_transforms_incomplete: "future transformations are not complete",
      baseline_contains_scenario_assumption: "the baseline contains a scenario assumption",
      tail_tests_incomplete: "one or more 2125 tail outcomes lack supporting evidence",
    },
  },
  zh: {
    meta: {
      title: "世纪城市指数 — Morris Liu",
      description: "以透明、可版本化的条件情景比较功能性都市区的长期韧性与机会。",
    },
    nav: { index: "指数", method: "方法", releases: "版本", language: "English" },
    runtime: {
      loading: "正在载入不可变发布数据。",
      ready: "发布数据已载入。",
      loadError: "发布数据载入失败，交互控件暂不可用。",
      metric: "指标",
      officialResult: "官方结果",
      range: "稳健–上行范围",
      confidence: "置信度",
      tail: "尾部状态",
    },
    hero: {
      title: "世纪城市指数",
      intro: "用于追问：在不断变化的世纪里，哪些城市系统可能继续宜居、有能力且保持连接？",
      caveat: "这是条件情景，不是事实预言或行动建议。",
      chartTitle: "一座城市，多种未来",
      chartNote: "仅展示结构，并非城市结果",
      robust: "稳健",
      median: "中位",
      upside: "上行",
    },
    release: {
      release: "发布",
      asOf: "截至",
      model: "模型",
      data: "数据",
      boundary: "边界",
      sourceManifest: "来源清单",
      researchPreview: "研究预览",
      research_preview: "研究预览",
      candidate: "候选版本",
      published: "已发布",
      immutable: "不可变发布",
      checksums: "来源与输出校验和",
      reviewed: "版本化证据审查记录",
      download: "打开发布 JSON",
    },
    controls: {
      targetYear: "目标年份",
      resultMode: "结果类型",
      robust: "稳健",
      median: "中位",
      upside: "上行",
      lifetime: "Lifetime",
    },
    compare: {
      title: "比较首批城市",
      intro: "这是刻意保持多样性的验证面板，全部绑定到同一个全球一致的功能性都市区产品。",
      notice: "目前没有城市通过 v1 排名资格。缺失证据继续保持缺失。",
      compare: "比较",
      clear: "清空比较",
      selected: "已选城市",
      empty: "请从表格中选择最多三座城市。",
      why: "为什么没有排名？",
      columns: {
        city: "城市 / FUA",
        result: "结果",
        range: "范围",
        confidence: "置信度",
        tail: "尾部",
        evidence: "证据",
      },
      inAudit: "审核中",
      reviewed: "已核查 · 查看证据",
      notRanked: "未排名",
      notRankedDefinition: "尚未满足资格门槛",
      confidenceDefinition: "至少一项置信度维度缺少支撑",
      noClaimDefinition: "不作出判断",
      selectCity: "选择城市进行比较",
      openCity: "打开城市证据",
    },
    city: {
      boundaryPending: "边界范围未获验证",
      boundaryVerified: "边界映射已验证",
      notRanked: "未排名",
      overview: "概览",
      evidence: "证据",
      sources: "来源",
      eightDimensions: "八个维度",
      result: "结果",
      confidence: "置信度",
      evidenceStatus: "证据",
      inAudit: "审核中",
      subpillars: "子支柱",
      noEvidence: "尚无评分证据通过本发布的资格门槛。",
      eligibilityReasons: "查看资格阻塞项",
      boundaryRecord: "边界记录",
      eFuaIds: "eFUA ID",
      urbanCentreIds: "城市中心 ID",
      sourceNames: "源数据名称",
      localLanguages: "本地证据要求语言",
      audit: "证据核查结论",
      usable_observation: "找到本地观测；尚未满足评分适配",
      context_only: "仅作背景；不计入城市评分",
      insufficient_evidence: "本维度证据不足",
      observationBoundary: "观测地理范围审核",
    },
    dimensions: {
      PCS: { name: "自然与气候安全", weight: 15 },
      GSS: { name: "战争与地缘安全", weight: 15 },
      ISR: { name: "制度与社会韧性", weight: 15 },
      RES: { name: "关键资源安全", weight: 10 },
      MED: { name: "医疗体系能力", weight: 15 },
      LON: { name: "长寿技术转化", weight: 10 },
      TEC: { name: "前沿科技能力", weight: 10 },
      OPT: { name: "全球连接与退出能力", weight: 10 },
    },
    subpillars: {
      heat_humidity: "高温与湿热",
      flood_sea_level: "洪水与海平面",
      geophysical: "地质灾害",
      severe_weather_wildfire: "强天气与野火",
      organized_violence: "本地有组织暴力",
      regional_conflict: "地区与国家间冲突",
      strategic_exposure: "战略目标与胁迫暴露",
      governance: "治理与规则执行",
      adaptive_capacity: "财政与适应能力",
      social_cohesion: "社会凝聚力",
      emergency_recovery: "应急恢复",
      water: "水",
      food: "食物",
      energy: "能源",
      supply_chain: "供应链冗余",
      access: "可及性与财务保护",
      routine_quality: "常规与急症质量",
      specialist_capacity: "复杂专科能力",
      system_continuity: "系统连续性",
      translation: "长寿专项转化",
      trial_maturity: "临床试验成熟度",
      regulatory_adoption: "监管采用",
      resident_access: "居民可获得性",
      knowledge_output: "前沿知识产出",
      industry_density: "企业与产业密度",
      digital_infrastructure: "算力与数字基础设施",
      diffusion: "技术扩散",
      transport_redundancy: "国际交通冗余",
      legal_mobility: "法律迁移与退出",
      asset_portability: "资产可携带性",
      network_continuity: "外部网络连续性",
    },
    myCci: {
      title: "我的 CCI",
      intro: "这里只调整八维权重；正式发布、置信度、来源和尾部状态始终不变。",
      total: "合计",
      reset: "恢复官方权重",
      personalResult: "个人结果",
      unavailable: "在未满足排名资格时不可计算。",
      weightLabel: "权重",
    },
    tail: {
      title: "尾部测试",
      status: "状态",
      note: "说明",
      unassessed: "未评估",
      insufficient: "已审证据不足以判定 2125 年结果",
      pass: "通过",
      watch: "关注",
      fail: "未通过",
      fatal_heat_humidity: "致命高温与湿热",
      permanent_inundation: "永久性淹没",
      geophysical_catastrophe: "地质巨灾",
      conflict_strategic_exposure: "冲突与战略暴露",
      essential_system_interruption: "关键系统长期中断",
    },
    evidenceLevels: {
      city_observation: { title: "城市观测", note: "在城市或 FUA 内直接观测。" },
      national_prior: { title: "国家先验", note: "从国家层面的条件推断。" },
      scenario_assumption: { title: "情景假设", note: "前瞻性或模型化的情景输入。" },
      missing: "缺失证据始终可见，不做静默填补。",
    },
    method: {
      title: "指数如何工作",
      intro: "从证据到条件结果的完整可见链条；语言模型不参与打分。",
      steps: [
        { number: "01", title: "观测", note: "城市观测与合格先验" },
        { number: "02", title: "归一化", note: "固定的差 / 参考 / 好锚点" },
        { number: "03", title: "投影", note: "基线 + 期限 × 情景变化 × 观测敏感度" },
        { number: "04", title: "汇总", note: "P20 稳健 / P50 中位 / P80 上行" },
        { number: "05", title: "门槛", note: "置信度、敏感性、资格与尾部测试" },
      ],
      scenariosTitle: "二十七个核心情景",
      climate: "气候",
      geopolitics: "地缘政治",
      medicine: "医学",
      climateStates: ["稳定", "中间", "高压力"],
      geopoliticsStates: ["合作", "碎片化", "升级"],
      medicineStates: ["渐进", "衰老科学突破", "再生平台"],
      unweighted: "情景网格不设权重，也不假装知道各情景的发生概率。",
      confidenceTitle: "置信度不取平均",
      confidenceMeasures: ["地理适配", "来源独立性", "时效性", "方法与溯源", "期限支撑"],
      weakest: "总体置信度取最弱等级。",
      lifetime:
        "Lifetime 是从发布日期到目标年的 Point 结果无折现时间加权平均，并在目标年份之间线性插值。",
    },
    governance: {
      title: "不预设权威的数据治理",
      intro: "CCI 不预设国际组织、政府、NGO、公司、遥感产品或英语指数天然中立。",
      principles: [
        "数字如何产生与谁发布分开分类。",
        "保留完整上游谱系，避免两个品牌共用一套数据却被当作两份独立证据。",
        "每座首批城市的八个维度都必须完成本地语言证据检索。",
        "有争议的输入采用替代源重算；不平均意识形态阵营，也不添加纠偏系数。",
      ],
      manifest: "来源清单",
      manifestSummary: "打开候选来源家族及其已知局限",
      source: "来源",
      role: "发布角色",
      mechanism: "生产机制",
      limits: "已知覆盖局限",
      applied: "已应用",
      catalogued: "已收录，未评分",
      context_only: "仅作背景",
      fullPolicy: "阅读完整的数据与偏差治理政策",
    },
    releases: {
      title: "发布历史",
      release: "发布",
      asOf: "截至",
      model: "模型",
      data: "数据",
      boundary: "边界",
      status: "状态",
    },
    correction: {
      title: "质疑证据",
      intro: "发现更可靠的来源或错误转换？请提交城市、指标、发布版本、理由和可核查来源。",
      link: "在 GitHub 提交纠错",
    },
    footer: {
      methodology: "方法论",
      governance: "数据与偏差治理",
      manifest: "来源清单",
      back: "返回 Morris Liu",
    },
    reasons: {
      boundary_needs_review: "FUA 范围未获验证",
      indicator_registry_incomplete: "指标注册表尚未冻结",
      subpillar_evidence_incomplete: "至少一个子支柱没有可计算证据",
      indicator_provenance_incomplete: "至少一个评分输入缺少完整溯源",
      observed_coverage_below_85: "观测覆盖率低于 85%",
      local_evidence_packs_incomplete: "本地语言证据包不完整",
      alternative_source_checks_incomplete: "所需替代来源检查不完整",
      source_sensitivity_missing: "来源替代敏感性尚未记录",
      unresolved_source_conflict: "来源冲突可能改变资格",
      confidence_grade_d: "至少一个置信度维度为 D",
      future_transforms_incomplete: "未来转换规则尚不完整",
      baseline_contains_scenario_assumption: "基线包含情景假设",
      tail_tests_incomplete: "至少一项 2125 尾部结果缺少判定依据",
    },
  },
} as const;
